name: Build fireboom production binary from release branch
on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      FB_VERSION: ${{ gitea.ref_name }}
    steps:
      - uses: https://git.fireboom.io/actions/checkout@v2
        with:
          submodules: recursive
      # - name: Set up Go
      #   uses: https://git.fireboom.io/actions/setup-go@v3
      #   with:
      #     go-version: 1.21.8
      - name: Install & Build
        env:
          GOPROXY: "https://goproxy.cn"
        run: |
          wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
          rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.1.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          echo "go installed"
          go mod tidy
          echo "mod tidy done"
          sh scripts/build-all.sh
          echo "build done"
          sh scripts/tar-all.sh
          echo "tar done"
          sh scripts/clear-bin.sh
          echo "clear bin done"
      - name: R2 Upload Action
        uses: https://git.fireboom.io/ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: fb-bin
          source-dir: release
          destination-dir: ./prod
      