name: Build base builder docker image
on:
  push:
    paths:
      - base.builder.Dockerfile
      - .gitea/workflows/build-base-builder-docker.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - uses: https://git.fireboom.io/actions/checkout@v2
      - name: Set up QEMU
        uses: https://git.fireboom.io/docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: https://git.fireboom.io/docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: https://git.fireboom.io/docker/login-action@v3
        with:
          registry: 192.168.211.101:8090
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Build and push
        uses: https://git.fireboom.io/docker/build-push-action@v5
        with:
          push: true
          file: base.builder.Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            192.168.211.101:8090/fireboomapi/base-builder-fireboom:latest