name: Build docker production image for release branch
on:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          FB_VERSION: ${{ github.ref_name }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            fireboomapi/fireboom:${{ github.ref_name }}